name: vscode-spring-boot-tools
description: |
  VS Code Language Server for Spring Boot
  VSCode extension and Language Server providing support for working with Spring Boot application.properties, application.yml and .java files.

  Note: this extension has a dependency on VS Code extension of Language Support for Java™ by Red Hat
homepage: https://github.com/spring-projects/sts4
licenses:
  - EPL-1.0
languages:
  - Java
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:github/indika-dev/repackage-sbt@2.2.2026041100
  asset:
    file: VMware.vscode-spring-boot.vsix

schemas:
  lsp: vscode:https://raw.githubusercontent.com/spring-projects/sts4/master/vscode-extensions/vscode-spring-boot/package.json

share:
  vscode-spring-boot-tools/jdtls/: extension/jars/
  vscode-spring-boot-tools/language-server.jar: extension/language-server/spring-boot-language-server.jar
